# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        storage.og_image:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/og_images'
            public_url: '/og_images'
