version: '3.6'

volumes:
  redis-data:

services:
  redis:
    extends:
      file: compose.yaml
      service: redis
    volumes:
      - redis-data:/data

  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - ./var/storage:/app/var/storage:rw