version: '3.6'

services:
  redis:
    extends:
      file: compose.yaml
      service: redis
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}