name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.30.0
        with:
          tools: symfony-cli

      - name: Install PHP dependencies
        run: symfony composer install --no-ansi

      - name: Check code style
        run: symfony composer check-cs -- --no-ansi

      - name: Analyze source code
        run: symfony composer phpstan -- --no-ansi
